export const PRODUCTS = [
  {
    name: "Produto 1",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 2",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 3",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 4",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 5",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 6",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 7",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
  {
    name: "Produto 8",
    description: "Teste teste",
    type: "Pallet",
    image: "/assets/pallet.png",
    price: "R$ 0.00",
  },
]