import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../frontend/styles/styles.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Projetinho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} selection:bg-[#aa9789] selection:text-white`}>
        <Navbar />
        <main className="min-h-[62vh] bg-[#f5f5f5] flex flex-col items-center w-full">
          {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
